package com.samy.gameboy.hardware.cartridge;


public enum CartridgeTypeEnum {

    ROM,ROM_MBC1,ROM_MBC1_RAM, ROM_MBC1__RAM_BATT,UNKNOWN,ROM_RAM,ROM_RAM_BATT,UNSUPPORTED_ROM_MMM1,UNSUPPORTED_ROM_MMM1_SRAM,UNSUPPORTED_ROM_MMM1_SRAM_BATT,
    ROM_MBC3_TIMER_BATT,ROM_MBC3_TIMER_RAM_BATT,ROM_MBC3,ROM_MBC3_RAM,ROM_MBC3_RAM_BATT,ROM_MBC5,ROM_MBC5_RAM, ROM_MBC5_RAM_BATT,
    ROM_MBC5_RUMBLE, ROM_MBC5_RUMBLE_RAM_BATT, ROM_MBC2, ROM_BC2_BATT, ROM_MBC5_RUMBLE_RAM
}
